---
dist: trusty
sudo: required
language: ruby

install:
  # Install Test Kitchen
  - gem install test-kitchen kitchen-docker kitchen-ansible

  # Check Test Kitchen version
  - kitchen --version


script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Test each system using Test Kitchen
  - kitchen test


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
