---
dist: trusty
sudo: required
language: ruby

install:
  # Install Ansible
  - sudo apt-get install -y python-pip
  - pip install ansible

  # Install Test Kitchen
  - gem install test-kitchen kitchen-docker kitchen-ansible

  # install testinfra
  - pip install testinfra

  # Check versions
  - kitchen --version
  - ansible --version
  - testinfra --version

before_script:
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Test each system using Test Kitchen
  - kitchen test


notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
