---
# Load variables based on OS type
- include_vars: '{{ item }}'
  with_first_found:
    - '../vars/os_{{ ansible_distribution }}.yml'
    - '../vars/os_{{ ansible_os_family }}.yml'
    - '../vars/os_RedHat.yml'
  when: gitlab_runner_rpm_os is not defined

- name: RPM | Install GitLab GPG key
  rpm_key:
    state: present
    key: https://packages.gitlab.com/gpg.key

- name: Add GitLab Runner rpm repo
  template:
    src: runner_gitlab-ci-multi-runner.repo.j2
    dest: /etc/yum.repos.d/runner_gitlab-ci-multi-runner.repo

- name: Install GitLab Runner
  package:
    name: gitlab-ci-multi-runner
    state: latest
