---

- name: RHEL | Install GitLab GPG key
  rpm_key:
    state: present
    key: https://packages.gitlab.com/gpg.key

- name: Add GitLab Runner rpm repo
  template:
    src: runner_gitlab-ci-multi-runner.repo.j2
    dest: /etc/yum.repos.d/runner_gitlab-ci-multi-runner.repo

- name: Install GitLab Runner
  yum:
    name: gitlab-ci-multi-runner
    state: latest
    update_cache: yes
