---
- name: Install GitLab Runner (Debian)
  include: install-debian.yml
  when: ansible_os_family == 'Debian'

- name: Install GitLab Runner (RPM)
  include: install-rpm.yml
  when: ansible_os_family == 'RedHat'
